services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    mem_limit: 64m
    memswap_limit: 128m

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    expose:
      - "8501"
    environment:
      - API_BASE_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    restart: unless-stopped
    mem_limit: 128m
    memswap_limit: 256m

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app
      - UPLOAD_FOLDER=/app/backend/uploads
    env_file:
      - .env
    restart: unless-stopped
    mem_limit: 196m
    memswap_limit: 256m
