services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    expose:
      - "8501"
    environment:
      - API_BASE_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app
      - UPLOAD_FOLDER=/app/backend/uploads
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 384M
        reservations:
          cpus: '0.3'
          memory: 256M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
